# Generated by Django 5.2.3 on 2025-06-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
